name: 'http://dashcunning.com'
favicon: null
layout_spectrum: 0.5644406646024436
typography_spectrum: 0.8211260228417814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9708031755872071
  lightness: 0.6539425477385521
  saturation: 0.6369489906355739
  rhythmicContrast: 0.3457113588228822
purpose: []
